### ISSUE TITLE
Update to 2.0 version of cats-core and cats-effect

### ISSUE THREAD

**Issue by LiuVII** [ccadllc/cedi-dtrace#108]
Trying to use the current version with the newer cats libs versions (2.0) breaks around using `parTraverse` methods and other parallel methods.

It would be very nice to update this project and continue using dtrace with newer cats libs.

**Comment by sbuzzard** [comment]
i'll do it this weekend.  I had meant to do it earlier.

**Comment by LiuVII** [comment]
Thanks so much 🎉
