### ISSUE TITLE
Span timing should be measured with System.nanoTime

### ISSUE THREAD

**Issue by fiadliel** [ccadllc/cedi-dtrace#12]
The current timing implementation uses `Instant.now`, and the difference between them, to measure the processing time of a span.

This is problematic for a few reasons, `Instant` is:
 - not guaranteed to be monotonic
 - not in any way guaranteed to be accurate
 - generally does not expose leap seconds
 - can be modified by NTP, etc.
 - it also currently only has millisecond accuracy, but this is the least of its issues

I think that for reliable timing, `System.nanoTime` should be used instead.

As this is not in any way related to the current "human" time, it has to be stored in addition to the current time (I note also that both values are stored in the Comcast Money implementation).

I have a working version of this, if you'd like a PR.

**Comment by mpilquist** [comment]
We intentionally used `System.currentTimeMillis` to avoid the performance hit of `nanoTime` but that's a tradeoff folks should be able to make on an app by app basis. For apps with lots and lots of spans that are all very fast to execute, all of the calls to `nanoTime` can end up being a hotspot. Any ideas on how we could make the time source configurable?

**Comment by fiadliel** [comment]
Even though `java.time.Clock` can offer more precision, e.g. https://bugs.openjdk.java.net/browse/JDK-8068730 - the Java Time-scale is based on UTC-SLS, so it's not always accurate for measuring intervals. So I don't think that offering an implicit `Clock` would be of much use, where accuracy is wanted.

The obvious configuration is a function might be `Instant => F[Long]` (with the potential for reusing information from the `Instant` you already have). First look at an appropriate implicit, say `NowTimeSource[F[_]]` - infects API in many places, and there's a strong danger of incoherent instances. Seems better, maybe, to add to `TraceSystem[F[_]]`? Either a sealed trait for a number of blessed options, or more flexibly, the above function signature.

**Comment by sbuzzard** [comment]
For our 1.5 release which targets cats-effect 1.0 I was thinking of updating dtrace to use an implicit Timer, providing a cats effect clock which provides  real time (currenttimemillis) or monotonic (nanotime) variants and provide an ADT in TraceSystem with these choices and assoc TimeUnit. Or could store an explicit cats effect Timer[F] in TraceSystem.

**Comment by sbuzzard** [comment]
cedi-dtrace 1.5.0-RC1 now has the ability to allow the user to specify a time precision using a `cats.effect.Clock[F]` (defaulting to the default implementation in that library).  See #30
