### ISSUE TITLE
implement b3 single format

### ISSUE THREAD

**Issue by codefromthecrypt** [ccadllc/cedi-dtrace#37]
there's a new compressed variant of b3: https://github.com/openzipkin/b3-propagation

It probably should be attempted on extract even when you expect typical b3. Up to you, though.

This impl might be similar enough to be handy! https://github.com/kamon-io/Kamon/issues/550

**Comment by sbuzzard** [comment]
Sorry, completely missed this - will add into our next 2.0 RC

**Comment by sbuzzard** [comment]
Implemented in #61
